# Generated by Django 6.0.3 on 2026-06-11 09:54

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce_id_ref', models.IntegerField(verbose_name='ID Annonce')),
                ('annonce_titre', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre annonce')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255, verbose_name='Public ID Cloudinary')),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_uploadees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Image d'annonce",
                'ordering': ['annonce_id_ref', 'ordre', '-est_principale'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce_id_ref', models.IntegerField(blank=True, null=True, verbose_name='ID Annonce')),
                ('annonce_titre', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre annonce')),
                ('sujet', models.CharField(default='Sans sujet', max_length=200, verbose_name='Sujet')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone de contact')),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('archive', 'Archivé')], default='non_lu', max_length=20, verbose_name='Statut')),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('nouveau_message', 'Nouveau message reçu'), ('reponse_vendeur', 'Le vendeur a répondu')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('annonce_id', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReponseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('message_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='messagerie.message', verbose_name='Message original')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['destinataire', 'statut'], name='messagerie__destina_7cd82f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur'], name='messagerie__expedit_78c39b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'est_lue'], name='messagerie__destina_8e9785_idx'),
        ),
    ]
